FROM maven:3.9.11-eclipse-temurin-24-alpine

WORKDIR /app

# COPY .mvn/ .mvn
# COPY mvnw pom.xml ./
# RUN ./mvnw dependency:go-offline -DskipTests

# COPY . .

EXPOSE 8088

CMD ["./mvnw", "spring-boot:run"]