spring:
  config:
    import: file:.env[.properties]
    
  application:
    name: server

  # datasource:
  #   url: jdbc:postgresql://localhost:5432/config_server
  #   username: postgres
  #   password: postgres
  #   driver-class-name: org.postgresql.Driver
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
          jdbc:
              '[batch_size]': 50  # Batch size for Hibernate JDBC operations
              '[order_inserts]': true  # Order inserts for Hibernate
              '[order_updates]': true  # Order updates for Hibernate
  profiles:
    active: jdbc
  
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
      destination: springCloudBus
      trace:
        enabled: true
    config:
      server:
        jdbc:
          enabled: false
        # git:
        #   uri: file:///../../../
        #   clone-on-start: true
        #   default-label: main
        #   timeout: 10

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  output:
    ansi:
      enabled: always
  
  threads:
    virtual:
      enabled: true

springdoc:
  api-docs:
    path: ${OPENAPI_API_DOCS}
  swagger-ui:
    path: ${OPENAPI_SWAGGER_UI}


server:
  port: 8088
  servlet:
    context-path: /config

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    busrefresh:
      access: unrestricted

# logging:
#   file:
#     name: configServer.log
logging:
  level:
    '[org.springframework.cloud.bus]': DEBUG
    '[org.springframework.amqp]': DEBUG