spring:
  application:
    name: server

  datasource:
    url: jdbc:postgresql://localhost:5432/config_server
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
          jdbc:
              '[batch_size]': 50  # Batch size for Hibernate JDBC operations
              '[order_inserts]': true  # Order inserts for Hibernate
              '[order_updates]': true  # Order updates for Hibernate
  profiles:
    active: jdbc
  
  cloud:
    config:
      server:
        jdbc:
          enabled: false
        # git:
        #   uri: file:///../../../
        #   clone-on-start: true
        #   default-label: main
        #   timeout: 10

  output:
    ansi:
      enabled: always
  
  threads:
    virtual:
      enabled: true

springdoc:
  api-docs:
    path: /openapi/swagger/docs/api-docs
  swagger-ui:
    path: /openapi/swagger/docs/swagger-ui.html


server:
  port: 8088
  servlet:
    context-path: /config

# logging:
#   file:
#     name: configServer.log
