spring:
  application:
    name: server

  datasource:
    url: jdbc:postgresql://localhost:5432/config_server
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
          jdbc:
              '[batch_size]': 50  # Batch size for Hibernate JDBC operations
              '[order_inserts]': true  # Order inserts for Hibernate
              '[order_updates]': true  # Order updates for Hibernate
  profiles:
    active: jdbc, git
  
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT key, value FROM configuration_entries WHERE application=? AND profile=? AND label=?
        git:
          uri: file:///../../../
          clone-on-start: true
          default-label: main
          timeout: 10

  output:
    ansi:
      enabled: always

server:
  port: 8088
  servlet:
    context-path: /config

# logging:
#   file:
#     name: configServer.log